Added ui state listener: activity, fragment and view
raulccabreu/redukt pull request #28
Opened 2017-12-12 20:08 UTC by flaviokreis

- [x] Added ui state listener: activity, fragment and view

It closes #26

2017-12-12 22:01 UTC, raulccabreu reviewed
Good! Waiting the answers about my doubts :+1:

2017-12-12 22:01 UTC, raulccabreu commented on app/src/main/java/com/github/raulccabreu/redukt/ui/StateView.kt
> +    override fun setVisibility(visibility: Int) {
I don't think 100% sure that is necessary a hide/show register and unregister mechanism at views, if we will add this, maybe at activity and fragment its necessary to implement this behavior too at resume/show with the `changeStateWhenHidden` method (suggest to change the method name to: `listenChangesWhenHidden`).

2017-12-12 22:01 UTC, raulccabreu commented on app/src/main/java/com/github/raulccabreu/redukt/ui/StateActivity.kt
> +abstract class StateActivity<T> : AppCompatActivity(), StateListener<T> {
What do you think about ReduktView, ReduktActivity and ReduktFragment or ReactiveView, ReactiveActivity....

2017-12-13 05:23 UTC, niltonvasques requested changes
Great work man! Those classes make more easy to bring redux to UI layer.

Would be good to have some tests to make sure that those things are working properly.

2017-12-13 05:23 UTC, niltonvasques commented on app/src/main/java/com/github/raulccabreu/redukt/ui/StateView.kt
> +    private fun registerReducer() {
Hmm! We aren't register it in a reducer, it is registering itself to hear state changes. Thus I think that a more appropriated name could be, registerStateChanges for example or other related.

2017-12-14 20:10 UTC, niltonvasques approved these changes

2017-12-14 20:13 UTC, merged