Add DebugMiddleware to debug actions and state changes.
raulccabreu/redukt pull request #41
Opened 2017-12-15 22:31 UTC by raulccabreu

- Create DebugMiddleware class.
- Add DebugMiddleware instance to middlewares and listeners
at Redukt start if debug mode on.
- Add debug flag at Redukt constructor with default false.
- Unify time spent and new debug flags.
- Prettify time spent log message.
- Update gradle and kotlin dependencies version.
- Change redukt version to the latest release at README import
instructions.

Close #27

2017-12-15 22:41 UTC, flaviokreis requested changes
This is good to test the app.

Is it good use the println, or use the Log.d ?

2017-12-15 22:41 UTC, flaviokreis commented on app/src/main/java/com/github/raulccabreu/redukt/middlewares/DebugMiddleware.kt
> + * Created by raulcca on 12/15/17.
You can remove unnecessary comments.

2017-12-15 22:41 UTC, flaviokreis commented on app/src/main/java/com/github/raulccabreu/redukt/middlewares/DebugMiddleware.kt
> +        println("------------------------------------------------------------")
You can remove this print.

2017-12-16 12:53 UTC, raulccabreu commented
@flaviokreis review changes maded!

2017-12-18 00:15 UTC, niltonvasques approved these changes
Really nice!

2017-12-18 01:09 UTC, flaviokreis approved these changes

2017-12-18 12:13 UTC, merged